import { useEffect, useState } from "react";
import axios from "axios";
import { Search, ArrowRight, Star, ShieldCheck, MapPin, LogOut, UserRound, ChevronLeft, HeartHandshake, Plus, X } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const heroImage = "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1400&q=85";
const serviceImages = { Limpeza:"https://images.unsplash.com/photo-1672860044506-e3ec09653e82?auto=format&fit=crop&w=700&q=80", Elétrica:heroImage, Hidráulica:"https://images.unsplash.com/photo-1676210133055-eab6ef033ce3?auto=format&fit=crop&w=700&q=80", Pintura:"https://images.unsplash.com/photo-1562259949-e8e7687d7828?auto=format&fit=crop&w=700&q=80" };
const demoProviders = [{id:"demo-1",name:"Marina Alves",category:"Limpeza e organização",rating:4.9,reviews:32,price:"a partir de R$ 120",initials:"MA"},{id:"demo-2",name:"Rafael Costa",category:"Elétrica residencial",rating:4.8,reviews:18,price:"a partir de R$ 90",initials:"RC"},{id:"demo-3",name:"Júlia Martins",category:"Pintura e reparos",rating:5.0,reviews:27,price:"a partir de R$ 150",initials:"JM"}];

function formatError(error) { const detail = error?.response?.data?.detail; return typeof detail === "string" ? detail : "Não foi possível concluir. Tente novamente."; }

export default function App() {
  const [user, setUser] = useState(null); const [view, setView] = useState("welcome"); const [auth, setAuth] = useState(null); const [services, setServices] = useState([]); const [category, setCategory] = useState(""); const [providers, setProviders] = useState(demoProviders); const [message, setMessage] = useState("");
  useEffect(() => { axios.get(`${API}/services`).then(r=>setServices(r.data)).catch(()=>setServices([{id:"cleaning",name:"Limpeza",icon:"✦",tone:"mint",description:"Casa leve, rotina tranquila"},{id:"electric",name:"Elétrica",icon:"ϟ",tone:"gold",description:"Energia funcionando bem"},{id:"plumbing",name:"Hidráulica",icon:"◒",tone:"blue",description:"Cuidado para cada detalhe"},{id:"painting",name:"Pintura",icon:"◉",tone:"rose",description:"Novas cores para viver"},{id:"gardening",name:"Jardinagem",icon:"⌁",tone:"green",description:"Mais vida nos seus espaços"},{id:"assembly",name:"Montagem",icon:"⊞",tone:"violet",description:"Tudo no lugar certo"}])); axios.get(`${API}/auth/me`,{withCredentials:true}).then(r=>{setUser(r.data);setView("home")}).catch(()=>{}); }, []);
  const search = (cat="", q="") => { setCategory(cat); setView("home"); axios.get(`${API}/providers`,{params:{category:cat,q},withCredentials:true}).then(r=>setProviders(r.data)).catch(()=>setProviders(demoProviders)); };
  const logout = async () => { await axios.post(`${API}/auth/logout`,{}, {withCredentials:true}).catch(()=>{}); setUser(null); setView("welcome"); };
  if (auth) return <AuthModal mode={auth} close={()=>setAuth(null)} onSwitch={()=>setAuth(auth==="login"?"register":"login")} onSuccess={(u)=>{setUser(u);setAuth(null);setView("home")}} />;
  return <div className="app-shell">
    <nav className="topbar"><button className="brand" data-testid="brand-home-button" onClick={()=>setView(user?"home":"welcome")}><span className="brand-mark">P</span><span>Pro<span>Mão</span></span></button><div className="nav-links"><button data-testid="nav-services-button" onClick={()=>setView("home")}>Encontrar serviço</button><button data-testid="nav-how-button" onClick={()=>setView("about")}>Como funciona</button></div><div className="nav-actions">{user ? <><button className="profile-chip" data-testid="profile-menu-button" onClick={()=>setView("profile")}><span className="avatar-small">{user.name?.[0]}</span>{user.name?.split(" ")[0]}</button><button className="icon-btn" data-testid="logout-button" onClick={logout} title="Sair"><LogOut size={18}/></button></> : <><button className="login-link" data-testid="login-open-button" onClick={()=>setAuth("login")}>Entrar</button><button className="dark-btn" data-testid="signup-open-button" onClick={()=>setAuth("register")}>Criar conta <ArrowRight size={16}/></button></>}</div></nav>
    {message && <div className="toast" data-testid="success-message">{message}<button data-testid="close-message-button" onClick={()=>setMessage("")}><X size={15}/></button></div>}
    {view === "welcome" && <Welcome onChoose={()=>setAuth("register")} onLogin={()=>setAuth("login")} />}
    {view === "home" && <Home services={services} category={category} search={search} providers={providers} user={user} onRequest={()=>user?setView("request"):setAuth("login")} />}
    {view === "profile" && <Profile user={user} logout={logout} onBack={()=>setView("home")} onMessage={setMessage} />}
    {view === "request" && <RequestForm onBack={()=>setView("home")} onDone={(m)=>{setMessage(m);setView("home")}} />}
    {view === "about" && <About onBack={()=>setView("home")} />}
    <footer><span>ProMão</span><span>Serviços de confiança, perto de você.</span><span>© 2025</span></footer>
  </div>;
}

function Welcome({onChoose,onLogin}) { return <main className="welcome"><section className="welcome-copy"><div className="eyebrow"><span className="live-dot"/> A rede que faz acontecer</div><h1>Seu tempo merece<br/><em>boas escolhas.</em></h1><p>Encontre profissionais de confiança para cuidar do que importa — ou faça seu trabalho chegar a quem precisa.</p><div className="welcome-actions"><button className="primary-btn" data-testid="choose-client-button" onClick={()=>onChoose("client")}>Sou cliente <ArrowRight size={18}/></button><button className="outline-btn" data-testid="choose-provider-button" onClick={()=>onChoose("provider")}>Sou prestador <Plus size={18}/></button></div><div className="trust-row"><ShieldCheck size={19}/><span>Perfis verificados</span><span className="divider"/><HeartHandshake size={19}/><span>Comunidade que recomenda</span></div></section><section className="welcome-visual"><img src={heroImage} alt="Profissional trabalhando em uma instalação" data-testid="welcome-hero-image"/><div className="image-note"><div className="avatar-stack"><span>MA</span><span>RC</span><span>JM</span></div><div><b>4.9 / 5</b><small>avaliação da comunidade</small></div><Star className="yellow-star" fill="currentColor"/></div></section><div className="scroll-hint">explore a rede <ArrowRight size={14}/></div></main>; }

function Home({services,category,search,providers,user,onRequest}) { const [query,setQuery]=useState(""); return <main className="home-page"><header className="page-intro"><div><div className="eyebrow">{user ? `Olá, ${user.name?.split(" ")[0]} 👋` : "A sua próxima solução está aqui"}</div><h1>O que você precisa<br/><em>resolver hoje?</em></h1></div><div className="location"><MapPin size={17}/><span>São Paulo, SP</span><ChevronLeft size={15} className="rotate"/></div></header><div className="search-line"><div className="search-box"><Search size={20}/><input data-testid="service-search-input" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search("",query)} placeholder="Busque por serviço ou profissional"/><button data-testid="service-search-button" onClick={()=>search("",query)}><ArrowRight size={19}/></button></div><button className="need-btn" data-testid="post-need-button" onClick={onRequest}>Descrever uma necessidade <Plus size={17}/></button></div><section className="category-section"><div className="section-heading"><div><span className="section-kicker">EXPLORE POR CATEGORIA</span><h2>Feito para a sua rotina</h2></div><button data-testid="all-categories-button" onClick={()=>search("")}>ver todas <ArrowRight size={15}/></button></div><div className="category-grid">{services.map(s=><button className={`category-tile ${category===s.name?"selected":""}`} data-testid={`category-${s.id}-button`} key={s.id} onClick={()=>search(s.name)}><span className={`tile-icon ${s.tone}`}>{s.icon}</span><span className="tile-text"><b>{s.name}</b><small>{s.description}</small></span><ArrowRight size={15}/></button>)}</div></section><section className="providers-section"><div className="section-heading"><div><span className="section-kicker">{category ? `PROFISSIONAIS EM ${category.toUpperCase()}` : "BONS PROFISSIONAIS, BOAS HISTÓRIAS"}</span><h2>Recomendados para você</h2></div><button data-testid="see-providers-button" onClick={()=>search(category)}>ver todos <ArrowRight size={15}/></button></div><div className="provider-grid">{providers.map((p,i)=><article className="provider-card" key={p.id} data-testid={`provider-card-${i}`}><div className={`provider-photo photo-${i}`}><span>{p.initials}</span><button data-testid={`favorite-provider-${i}`} className="heart-btn"><HeartHandshake size={17}/></button></div><div className="provider-info"><div className="provider-name"><h3>{p.name}</h3><ShieldCheck size={16}/></div><p>{p.category}</p><div className="rating"><Star size={15} fill="currentColor"/><b>{p.rating}</b><span>({p.reviews} avaliações)</span></div><div className="provider-bottom"><strong>{p.price}</strong><button data-testid={`request-provider-${i}`} onClick={onRequest}>Ver perfil <ArrowRight size={15}/></button></div></div></article>)}</div></section></main>; }

function AuthModal({mode,close,onSwitch,onSuccess}) { const [role,setRole]=useState("client"); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const isLogin=mode==="login"; const submit=async(e)=>{e.preventDefault();setError("");try{const url=isLogin?"/auth/login":"/auth/register";const payload=isLogin?{email,password}:{name,email,password,role};const r=await axios.post(API+url,payload,{withCredentials:true});onSuccess(r.data)}catch(err){setError(formatError(err))}}; return <div className="modal-backdrop"><div className="auth-modal"><button className="modal-close" data-testid="auth-close-button" onClick={close}><X size={20}/></button><div className="auth-brand"><span className="brand-mark">P</span><span>Pro<span>Mão</span></span></div><span className="section-kicker">{isLogin?"BEM-VINDO DE VOLTA":"COMECE POR AQUI"}</span><h2>{isLogin?"Entre na sua conta":"Qual é o seu papel nessa rede?"}</h2>{!isLogin&&<div className="role-toggle"><button type="button" className={role==="client"?"active":""} data-testid="role-client-option" onClick={()=>setRole("client")}>Sou cliente<small>Encontro quem resolve</small></button><button type="button" className={role==="provider"?"active":""} data-testid="role-provider-option" onClick={()=>setRole("provider")}>Sou prestador<small>Ofereço meu trabalho</small></button></div>}<form onSubmit={submit} data-testid="auth-form">{!isLogin&&<label>Seu nome<input data-testid="auth-name-input" value={name} onChange={e=>setName(e.target.value)} required placeholder="Como podemos te chamar?"/></label>}<label>Seu e-mail<input data-testid="auth-email-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="voce@email.com"/></label><label>Senha<input data-testid="auth-password-input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="6" placeholder="mínimo de 6 caracteres"/></label>{error&&<div className="form-error" data-testid="auth-error-message">{error}</div>}<button className="primary-btn wide" data-testid="auth-submit-button">{isLogin?"Entrar na ProMão":"Criar minha conta"}<ArrowRight size={17}/></button></form><div className="or"><span/> ou <span/></div><button className="google-btn" data-testid="google-link-button" onClick={()=>setError("O vínculo com Google será ativado na próxima etapa.")}>G <span>Continuar com Google</span></button><p className="auth-switch">{isLogin?"Ainda não tem conta?":"Já tem uma conta?"} <button data-testid="auth-switch-button" onClick={onSwitch}>{isLogin?"Criar agora":"Entrar"}</button></p></div></div>; }

function RequestForm({onBack,onDone}) { const [form,setForm]=useState({service:"",category:"",description:"",budget:""}); const [error,setError]=useState(""); const submit=async(e)=>{e.preventDefault();try{await axios.post(`${API}/requests`,form,{withCredentials:true});onDone("Pedido publicado! Em breve você receberá propostas de profissionais.")}catch(err){setError(formatError(err))}}; return <main className="form-page"><button className="back-btn" data-testid="request-back-button" onClick={onBack}><ChevronLeft size={18}/> voltar</button><span className="section-kicker">NOVA SOLICITAÇÃO</span><h1>Conte o que você<br/><em>precisa resolver.</em></h1><form className="request-form" onSubmit={submit} data-testid="request-form"><label>Que serviço você procura?<input data-testid="request-service-input" required value={form.service} onChange={e=>setForm({...form,service:e.target.value})} placeholder="Ex.: instalar uma luminária"/></label><label>Categoria<select data-testid="request-category-select" required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Selecione</option><option>Limpeza</option><option>Elétrica</option><option>Hidráulica</option><option>Pintura</option><option>Jardinagem</option><option>Montagem</option></select></label><label>Explique um pouco mais<textarea data-testid="request-description-input" required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Detalhes ajudam o profissional a preparar uma proposta melhor"/></label><label>Você tem um orçamento em mente? <span className="optional">opcional</span><input data-testid="request-budget-input" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})} placeholder="Ex.: até R$ 250"/></label>{error&&<div className="form-error" data-testid="request-error-message">{error}</div>}<button className="primary-btn" data-testid="request-submit-button">Publicar pedido <ArrowRight size={17}/></button></form></main>; }

function Profile({user,logout,onBack,onMessage}) { return <main className="profile-page"><button className="back-btn" data-testid="profile-back-button" onClick={onBack}><ChevronLeft size={18}/> voltar</button><div className="profile-header"><span className="profile-avatar">{user?.name?.[0]}</span><div><span className="section-kicker">MEU ESPAÇO</span><h1>{user?.name}</h1><p>{user?.role==="provider"?"Prestador de serviços":"Cliente da comunidade"} · {user?.email}</p></div></div><div className="profile-columns"><section><h2>Seu próximo passo</h2><div className="profile-action"><div><b>{user?.role==="provider"?"Monte seu catálogo":"Encontre alguém para ajudar"}</b><p>{user?.role==="provider"?"Escolha categorias, tarefas e seus preços.":"Publique uma necessidade e receba propostas."}</p></div><ArrowRight size={18}/></div></section><section><h2>Conta</h2><button className="list-action" data-testid="profile-google-link-button" onClick={()=>onMessage("Vínculo com Google preparado para a próxima etapa.")}><span>G</span>Vincular conta Google <ArrowRight size={16}/></button><button className="list-action" data-testid="profile-logout-button" onClick={logout}><LogOut size={16}/> Sair da conta <ArrowRight size={16}/></button></section></div></main>; }

function About({onBack}) { return <main className="about-page"><button className="back-btn" data-testid="about-back-button" onClick={onBack}><ChevronLeft size={18}/> voltar</button><span className="section-kicker">COMO FUNCIONA</span><h1>Confiança que<br/><em>circula.</em></h1><div className="about-grid"><div><span className="step">01</span><h2>Escolha seu caminho</h2><p>Entre como cliente ou prestador. Seu espaço se adapta ao que você precisa fazer.</p></div><div><span className="step">02</span><h2>Combine com clareza</h2><p>Veja categorias, preços transparentes e profissionais recomendados pela comunidade.</p></div><div><span className="step">03</span><h2>Compartilhe a experiência</h2><p>Avalie, recomende e ajude a construir uma rede mais confiável para todos.</p></div></div></main>; }